export enum FeatureFlagKey {
  FORCE_UPDATE = 'FORCE_UPDATE',
  MAINTENANCE_MODE = 'MAINTENANCE_MODE',
  EVENT_MODULES_RESTRICTIONS = 'EVENT_MODULES_RESTRICTIONS',
  RESTRICTIONS_ADMIN = 'RESTRICTIONS_ADMIN',
  AUTH_LOGIN = 'AUTH_LOGIN',
  AUTH_REGISTER = 'AUTH_REGISTER',
  AUTH_FORGOT_PASSWORD = 'AUTH_FORGOT_PASSWORD',
  AUTH_GOOGLE = 'AUTH_GOOGLE',
  AUTH_APPLE = 'AUTH_APPLE',
}
